clear all;
close all;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Checking the random number generation for%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% variable y and y bar
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 


% Note that we only calculate the pdf distribution function of variable y
% this is because pdf of y and yprime are the same


 cd('/home/prateek/DATA_CD/codes/final_PL/Wall_pressure_calculation_final_code/copy5/Three_dimensional_Gaussian_correlation_inputgabriele');
 
x =  importdata('PDF.txt');
a =  0.3; % constant chosen for variance reduction see the main.f90 file 
b =5;
k = 0.313 ;
h = 0.4; 
nbins = 500; % generate histogram with 1000 bins equally spaced in the interval of interest

[f,real] = hist(x(:,2),nbins); 
pdf_y  =  ( exp(-b*k.*(real -(a*h/k)).^2)*sqrt(b)*sqrt(k)*2 ) / ( sqrt(pi) * ( erf( (a*sqrt(b))/(sqrt(k))  ) +erf( (sqrt(b)*(-a+k))/(sqrt(k)) ) )  ) ; 
% the above is the pdf for y, for complete expresion please refer to the 
% document Gaussian.pdf for explanation


figure()
bar(real,f/trapz(real,f));
hold on;
h = plot(real,pdf_y,'r');
set(h(1),'Color',[1.0 0.0 0],'LineStyle','-','Marker','none','LineWidth',2)
hold off;
xlabel('random number generated ','Fontsize',16)
ylabel('Normalized Frequency of \newline Random output generated','Fontsize',16)

set(gca,'fontsize',16);
ylim([0    2.5]);
xlim([-0.1 1.1]);
hleg1 = legend('Histogram \newline of Random output \newline generated by pdf','PDF y','location','Northeast');
set(hleg1,'FontSize',20);

%%
cd('/home/prateek/DATA_CD/codes/final_PL/Wall_pressure_calculation_final_code/Three_dimensional_Gaussian_correlation_inputgabriele/Results');
print(gcf,'-r300','-dpng','pdf y')
cd ..



%% Random number distribution for the variable k3 
clear all;
close all;

  
x =  importdata('PDF.txt');
c =  0.1265; % constant chosen for variance reduction see the main.f90 file 
nbins = 1000; % generate histogram with 1000 bins equally spaced in the interval of interest
d = 30 ; % this the limit of integration for the variable k3


[f,real] = hist(x(:,1),nbins); 
pdf_k3 = (c* (exp( -(real.^2.*c^2) /4) ))/ (sqrt(pi)*erf(c*d/2)  )  ; 
% the above is the pdf for y, for complete expresion please refer to the 
% document Gaussian.pdf for explanation


figure()
bar(real,f/trapz(real,f));
hold on;
h = plot(real,pdf_k3,'r');
set(h(1),'Color',[1.0 0.0 0],'LineStyle','-','Marker','none','LineWidth',2)
hold off;
xlabel('random number generated ','Fontsize',16)
ylabel('Normalized Frequency of \newline Random output generated','Fontsize',16)

set(gca,'fontsize',16);
ylim([0    0.08]);
xlim([-1 32]);
hleg1 = legend('Histogram \newline of Random output \newline generated by pdf','PDF k3','location','Northeast');
set(hleg1,'FontSize',20);



%%

cd('/home/prateek/DATA_CD/codes/final_PL/Wall_pressure_calculation_final_code/Three_dimensional_Gaussian_correlation_inputgabriele/Results');
print(gcf,'-r300','-dpng','pdf k3')
cd ..





%%
% Trash below
%%
% 
% clear all;
% %close all;
% 
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Checking the random number generation for%
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% variable r and r2
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  
% cd('/home/prateek/codes/Fortran/rootfinding/rootfinding');
%  
% x =  importdata('rand_out_r.txt');
% y = x(:,3); % the quasi random number generated
% cin = 4.5;
% [f,real] = hist(x(:,3),50);
% pdf = cin^2*real.*exp(-real*cin);
% 
% 
% 
% figure()
% bar(real,f/trapz(real,f));
% hold on;
% h = plot(real,pdf,'r');
% set(h(1),'Color',[1.0 0.0 0],'LineStyle','-','Marker','none','LineWidth',2)
% hold off;
% xlabel('realization ','Fontsize',20)
% ylabel('Density','Fontsize',20)
% 
% set(gca,'fontsize',16);
% ylim([0    2.5]);
% xlim([0 2.5]);
% hleg1 = legend('Rand output','PDF','location','Northeast');
% set(hleg1,'FontSize',20);
% 
% %%
% clear all;
% close all;
% 
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% Checking the random number generation for%
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% variable r and r2
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  
% cd('/home/prateek/codes/Fortran/rootfinding/rootfinding');
%  
% x =  importdata('rand_out_r2.txt');
% y = x(:,2); % the quasi random number generated
% cin = 1.0;
% [f,real] = hist(x(:,2),50);
% pdf = 0.5*cin^3*(real.^2).*exp(-real*cin);
% 
% 
% 
% figure()
% bar(real,f/trapz(real,f));
% hold on;
% h = plot(real,pdf,'r');
% set(h(1),'Color',[1.0 0.0 0],'LineStyle','-','Marker','none','LineWidth',2)
% hold off;
% xlabel('realization ','Fontsize',20)
% ylabel('Density','Fontsize',20)
% 
% set(gca,'fontsize',16);
% ylim([0    2.5]);
% xlim([0 2.5]);
% hleg1 = legend('Rand output','PDF','location','Northeast');
% set(hleg1,'FontSize',20);
% 
% %% 
%  
% 
% 
% clear all;
% close all;
% 
%  
%  cd('/home/prateek/codes/PL_CDairfoil_v4_DP');
%  
% x =  importdata('PDF.txt');
% k1 = 20;
% d = 50;
% argx = atan(d/k1);
% [f,real] = hist(x(280000:300000,4),50);
% pdf = k1./((real.^2+k1^2)*atan(d/k1));
% 
% 
% 
% figure()
% bar(real,f/trapz(real,f));
% hold on;
% h = plot(real,pdf,'r');
% set(h(1),'Color',[1.0 0.0 0],'LineStyle','-','Marker','none','LineWidth',2)
% hold off;
% xlabel('realization ','Fontsize',20)
% ylabel('Density','Fontsize',20)
% 
% set(gca,'fontsize',16);
% 
% hleg1 = legend('Rand output','PDF','location','Northeast');
% set(hleg1,'FontSize',20);
% %%
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  
% cd('/home/prateek/codes/PL_CDairfoil_v2');
%  
% x =  importdata('pdf.txt');
% y = x(:,2); % the quasi random number generated
% cin = 1.0;
% [f,real] = hist(x(:,2),length(x(:,1)));
% pdf =  x(:,3);
% 
% 
% 
% figure()
% bar(real,f/trapz(real,f));
% hold on;
% h = plot(real,pdf,'r');
% set(h(1),'Color',[1.0 0.0 0],'LineStyle','-','Marker','none','LineWidth',2)
% hold off;
% xlabel('realization ','Fontsize',20)
% ylabel('Density','Fontsize',20)
% 
% set(gca,'fontsize',16);
% ylim([0    2.5]);
% xlim([0 2.5]);
% hleg1 = legend('Rand output','PDF','location','Northeast');
% set(hleg1,'FontSize',20);